// Code generated by go generate .internal/tools/generator; DO NOT EDIT.

package linkrelation

const (
	// About refers to a resource that is the subject of the link's context.
	//
	// Reference: [RFC6903], section 2
	About LinkRelation = "about"
	// Acl asserts that the link target provides an access control resource for the link context.
	//
	// Reference: [https://solidproject.org/TR/wac#acl-link-relation]
	Acl LinkRelation = "acl"
	// Alternate refers to a substitute for this context
	//
	// Reference: [HTML]
	Alternate LinkRelation = "alternate"
	// AMPHTML used to reference alternative content that uses the AMP profile of the HTML format.
	//
	// Reference: [AMP HTML]
	AMPHTML LinkRelation = "amphtml"
	// APICatalog refers to a list of APIs available from the Publisher of the link context.
	//
	// Reference: [RFC9727]
	APICatalog LinkRelation = "api-catalog"
	// Appendix refers to an appendix.
	//
	// Reference: [HTML 4.01 Specification]
	Appendix LinkRelation = "appendix"
	// AppleTouchIcon refers to an icon for the context. Synonym for icon.
	//
	// Reference: [Configuring Web Applications]
	AppleTouchIcon LinkRelation = "apple-touch-icon"
	// AppleTouchStartupImage refers to a launch screen for the context.
	//
	// Reference: [Configuring Web Applications]
	AppleTouchStartupImage LinkRelation = "apple-touch-startup-image"
	// Archives refers to a collection of records, documents, or other
	// materials of historical interest.
	//
	// Reference: [HTML5]
	Archives LinkRelation = "archives"
	// Author refers to the context's author.
	//
	// See also 'me'
	//
	// Reference: [HTML]
	Author LinkRelation = "author"
	// BlockedBy identifies the entity that blocks access to a resource
	// following receipt of a legal demand.
	//
	// Reference: [RFC7725]
	BlockedBy LinkRelation = "blocked-by"
	// Bookmark gives a permanent link to use for bookmarking purposes.
	//
	// Reference: [HTML]
	Bookmark LinkRelation = "bookmark"
	// C2PAManifest this link relation identifies the C2PA Manifest associated with the link context
	//
	// Reference: [Content Credentials : C2PA Technical Specification]
	C2PAManifest LinkRelation = "c2pa-manifest"
	// Canonical designates the preferred version of a resource (the IRI and its contents).
	//
	// Reference: [RFC6596]
	Canonical LinkRelation = "canonical"
	// Chapter refers to a chapter in a collection of resources.
	//
	// Reference: [HTML 4.01 Specification]
	Chapter LinkRelation = "chapter"
	// CiteAs indicates that the link target is preferred over the link context for the purpose of permanent citation.
	//
	// Reference: [RFC8574]
	CiteAs LinkRelation = "cite-as"
	// Collection the target IRI points to a resource which represents the collection resource for the context IRI.
	//
	// Reference: [RFC6573]
	Collection LinkRelation = "collection"
	// CompressionDictionary refers to a compression dictionary used for content encoding.
	//
	// Reference: [RFC 9842, Section 3]
	CompressionDictionary LinkRelation = "compression-dictionary"
	// Contents refers to a table of contents.
	//
	// Reference: [HTML 4.01 Specification]
	Contents LinkRelation = "contents"
	// ConvertedFrom the document linked to was later converted to the
	// document that contains this link relation.  For example, an RFC can
	// have a link to the Internet-Draft that became the RFC; in that case,
	// the link relation would be "convertedFrom".
	//
	// This relation is different than "predecessor-version" in that
	// "predecessor-version" is for items in a version control system.  It
	// is also different than "previous" in that this relation is used for
	// converted resources, not those that are part of a sequence of
	// resources.
	//
	// Reference: [RFC7991]
	ConvertedFrom LinkRelation = "convertedfrom"
	// Copyright refers to a copyright statement that applies to the
	// link's context.
	//
	// Reference: [HTML 4.01 Specification]
	Copyright LinkRelation = "copyright"
	// CreateForm the target IRI points to a resource where a submission form can be obtained.
	//
	// Reference: [RFC6861]
	CreateForm LinkRelation = "create-form"
	// Current refers to a resource containing the most recent
	// item(s) in a collection of resources.
	//
	// Reference: [RFC5005]
	Current LinkRelation = "current"
	// Deprecation refers to documentation (intended for human consumption) about the deprecation of the link's context.
	//
	// Reference: [RFC9745], section 3
	Deprecation LinkRelation = "deprecation"
	// DescribedBy refers to a resource providing information about the
	// link's context.
	//
	// Reference: [Protocol for Web Description Resources (POWDER)]
	DescribedBy LinkRelation = "describedby"
	// Describes the relationship A 'describes' B asserts that
	// resource A provides a description of resource B. There are no
	// constraints on the format or representation of either A or B,
	// neither are there any further constraints on either resource.
	//
	// This link relation type is the inverse of the 'describedby'
	// relation type.  While 'describedby' establishes a relation from
	// the described resource back to the resource that describes it,
	// 'describes' established a relation from the describing resource to
	// the resource it describes.  If B is 'describedby' A, then A
	// 'describes' B.
	//
	// Reference: [RFC6892]
	Describes LinkRelation = "describes"
	// Disclosure refers to a list of patent disclosures made with respect to material for which 'disclosure' relation is specified.
	//
	// Reference: [RFC6579]
	Disclosure LinkRelation = "disclosure"
	// DNSPrefetch used to indicate an origin that will be used to fetch required resources for the link context, and that the user agent ought to resolve as early as possible.
	//
	// Reference: [HTML]
	DNSPrefetch LinkRelation = "dns-prefetch"
	// Duplicate refers to a resource whose available representations
	// are byte-for-byte identical with the corresponding representations of
	// the context IRI.
	//
	// This relation is for static resources.  That is, an HTTP GET
	// request on any duplicate will return the same representation.  It
	// does not make sense for dynamic or POSTable resources and should not
	// be used for them.
	//
	// Reference: [RFC6249]
	Duplicate LinkRelation = "duplicate"
	// Edit refers to a resource that can be used to edit the
	// link's context.
	//
	// Reference: [RFC5023]
	Edit LinkRelation = "edit"
	// EditForm the target IRI points to a resource where a submission form for
	// editing associated resource can be obtained.
	//
	// Reference: [RFC6861]
	EditForm LinkRelation = "edit-form"
	// EditMedia refers to a resource that can be used to edit media
	// associated with the link's context.
	//
	// Reference: [RFC5023]
	EditMedia LinkRelation = "edit-media"
	// Enclosure identifies a related resource that is potentially
	// large and might require special handling.
	//
	// Reference: [RFC4287]
	Enclosure LinkRelation = "enclosure"
	// External refers to a resource that is not part of the same site as the current context.
	//
	// Reference: [HTML]
	External LinkRelation = "external"
	// First an IRI that refers to the furthest preceding resource
	// in a series of resources.
	//
	// This relation type registration did not indicate a
	// reference.  Originally requested by Mark Nottingham in December
	// 2004.
	//
	// Reference: [RFC8288]
	First LinkRelation = "first"
	// GeoFeed refers to a resource with IP geofeed location information related to the link context.
	//
	// Reference: [RFC9877]
	GeoFeed LinkRelation = "geofeed"
	// Glossary refers to a glossary of terms.
	//
	// Reference: [HTML 4.01 Specification]
	Glossary LinkRelation = "glossary"
	// Help refers to context-sensitive help.
	//
	// Reference: [HTML]
	Help LinkRelation = "help"
	// Hosts refers to a resource hosted by the server indicated by
	// the link context.
	//
	// This relation is used in CoRE where links are retrieved as a
	// "/.well-known/core" resource representation, and is the default
	// relation type in the CoRE Link Format.
	//
	// Reference: [RFC6690]
	Hosts LinkRelation = "hosts"
	// Hub refers to a hub that enables registration for
	// notification of updates to the context.
	//
	// This relation type was requested by Brett Slatkin.
	//
	// Reference: [WebSub]
	Hub LinkRelation = "hub"
	// ICEServer conveys the STUN and TURN servers that can be used by an ICE agent to establish a connection with a peer.
	//
	// Reference: [RFC9725]
	ICEServer LinkRelation = "ice-server"
	// Icon refers to an icon representing the link's context.
	//
	// Reference: [HTML]
	Icon LinkRelation = "icon"
	// Index refers to an index.
	//
	// Reference: [HTML 4.01 Specification]
	Index LinkRelation = "index"
	// IntervalAfter refers to a resource associated with a time interval that ends before the beginning of the time interval associated with the context resource
	//
	// Reference: [Time Ontology in OWL] section 4.2.21
	IntervalAfter LinkRelation = "intervalafter"
	// IntervalBefore refers to a resource associated with a time interval that begins after the end of the time interval associated with the context resource
	//
	// Reference: [Time Ontology in OWL] section 4.2.22
	IntervalBefore LinkRelation = "intervalbefore"
	// IntervalContains refers to a resource associated with a time interval that begins after the beginning of the time interval associated with the context resource, and ends before the end of the time interval associated with the context resource
	//
	// Reference: [Time Ontology in OWL] section 4.2.23
	IntervalContains LinkRelation = "intervalcontains"
	// IntervalDisjoint refers to a resource associated with a time interval that begins after the end of the time interval associated with the context resource, or ends before the beginning of the time interval associated with the context resource
	//
	// Reference: [Time Ontology in OWL] section 4.2.24
	IntervalDisjoint LinkRelation = "intervaldisjoint"
	// IntervalDuring refers to a resource associated with a time interval that begins before the beginning of the time interval associated with the context resource, and ends after the end of the time interval associated with the context resource
	//
	// Reference: [Time Ontology in OWL] section 4.2.25
	IntervalDuring LinkRelation = "intervalduring"
	// IntervalEquals refers to a resource associated with a time interval whose beginning coincides with the beginning of the time interval associated with the context resource, and whose end coincides with the end of the time interval associated with the context resource
	//
	// Reference: [Time Ontology in OWL] section 4.2.26
	IntervalEquals LinkRelation = "intervalequals"
	// IntervalFinishedBy refers to a resource associated with a time interval that begins after the beginning of the time interval associated with the context resource, and whose end coincides with the end of the time interval associated with the context resource
	//
	// Reference: [Time Ontology in OWL] section 4.2.27
	IntervalFinishedBy LinkRelation = "intervalfinishedby"
	// IntervalFinishes refers to a resource associated with a time interval that begins before the beginning of the time interval associated with the context resource, and whose end coincides with the end of the time interval associated with the context resource
	//
	// Reference: [Time Ontology in OWL] section 4.2.28
	IntervalFinishes LinkRelation = "intervalfinishes"
	// IntervalIn refers to a resource associated with a time interval that begins before or is coincident with the beginning of the time interval associated with the context resource, and ends after or is coincident with the end of the time interval associated with the context resource
	//
	// Reference: [Time Ontology in OWL] section 4.2.29
	IntervalIn LinkRelation = "intervalin"
	// IntervalMeets refers to a resource associated with a time interval whose beginning coincides with the end of the time interval associated with the context resource
	//
	// Reference: [Time Ontology in OWL] section 4.2.30
	IntervalMeets LinkRelation = "intervalmeets"
	// IntervalMetBy refers to a resource associated with a time interval whose end coincides with the beginning of the time interval associated with the context resource
	//
	// Reference: [Time Ontology in OWL] section 4.2.31
	IntervalMetBy LinkRelation = "intervalmetby"
	// IntervalOverlappedBy refers to a resource associated with a time interval that begins before the beginning of the time interval associated with the context resource, and ends after the beginning of the time interval associated with the context resource
	//
	// Reference: [Time Ontology in OWL] section 4.2.32
	IntervalOverlappedBy LinkRelation = "intervaloverlappedby"
	// IntervalOverlaps refers to a resource associated with a time interval that begins before the end of the time interval associated with the context resource, and ends after the end of the time interval associated with the context resource
	//
	// Reference: [Time Ontology in OWL] section 4.2.33
	IntervalOverlaps LinkRelation = "intervaloverlaps"
	// IntervalStartedBy refers to a resource associated with a time interval whose beginning coincides with the beginning of the time interval associated with the context resource, and ends before the end of the time interval associated with the context resource
	//
	// Reference: [Time Ontology in OWL] section 4.2.34
	IntervalStartedBy LinkRelation = "intervalstartedby"
	// IntervalStarts refers to a resource associated with a time interval whose beginning coincides with the beginning of the time interval associated with the context resource, and ends after the end of the time interval associated with the context resource
	//
	// Reference: [Time Ontology in OWL] section 4.2.35
	IntervalStarts LinkRelation = "intervalstarts"
	// Item the target IRI points to a resource that is a member of the collection represented by the context IRI.
	//
	// Reference: [RFC6573]
	Item LinkRelation = "item"
	// Last an IRI that refers to the furthest following resource
	// in a series of resources.
	//
	// This relation type registration did not indicate a
	// reference. Originally requested by Mark Nottingham in December
	// 2004.
	//
	// Reference: [RFC8288]
	Last LinkRelation = "last"
	// LatestVersion points to a resource containing the latest (e.g.,
	// current) version of the context.
	//
	// Reference: [RFC5829]
	LatestVersion LinkRelation = "latest-version"
	// License refers to a license associated with this context.
	//
	// For implications of use in HTML, see: http://www.w3.org/TR/html5/links.html#link-type-license
	//
	// Reference: [RFC4946]
	License LinkRelation = "license"
	// LinkSet the link target of a link with the "linkset" relation
	// type provides a set of links, including links in which the link
	// context of the link participates.
	//
	// Reference: [RFC9264]
	LinkSet LinkRelation = "linkset"
	// LRDD refers to further information about the link's context,
	// expressed as a LRDD ("Link-based Resource Descriptor Document")
	// resource.  See [RFC6415] for information about
	// processing this relation type in host-meta documents. When used
	// elsewhere, it refers to additional links and other metadata.
	// Multiple instances indicate additional LRDD resources. LRDD
	// resources MUST have an "application/xrd+xml" representation, and
	// MAY have others.
	//
	// Reference: [RFC6415]
	LRDD LinkRelation = "lrdd"
	// Manifest links to a manifest file for the context.
	//
	// Reference: [Web App Manifest]
	Manifest LinkRelation = "manifest"
	// MaskIcon refers to a mask that can be applied to the icon for the context.
	//
	// Reference: [Creating Pinned Tab Icons]
	MaskIcon LinkRelation = "mask-icon"
	// Me links to a resource about the author of the link's context.
	//
	// See also 'author'
	//
	// Reference: [https://microformats.org/wiki/rel-me]
	Me LinkRelation = "me"
	// MediaFeed refers to a feed of personalised media recommendations relevant to the link context.
	//
	// Reference: [https://wicg.github.io/media-feeds/#discovery-of-media-feeds]
	MediaFeed LinkRelation = "media-feed"
	// Memento the Target IRI points to a Memento, a fixed resource that will not change state anymore.
	//
	// A Memento for an Original Resource is a resource that
	// encapsulates a prior state of the Original Resource.
	//
	// Reference: [RFC7089]
	Memento LinkRelation = "memento"
	// Micropub links to the context's Micropub endpoint.
	//
	// Reference: [Micropub]
	Micropub LinkRelation = "micropub"
	// ModulePreload refers to a module that the user agent is to preemptively fetch and store for use in the current context.
	//
	// Reference: [HTML]
	ModulePreload LinkRelation = "modulepreload"
	// Monitor refers to a resource that can be used to monitor changes in an HTTP resource.
	//
	// Reference: [RFC5989]
	Monitor LinkRelation = "monitor"
	// MonitorGroup refers to a resource that can be used to monitor changes in a specified group of HTTP resources.
	//
	// Reference: [RFC5989]
	MonitorGroup LinkRelation = "monitor-group"
	// Next indicates that the link's context is a part of a series, and
	// that the next in the series is the link target.
	//
	// Reference: [HTML]
	Next LinkRelation = "next"
	// NextArchive refers to the immediately following archive resource.
	//
	// Reference: [RFC5005]
	NextArchive LinkRelation = "next-archive"
	// NoFollow indicates that the context’s original author or publisher does not endorse the link target.
	//
	// Reference: [HTML]
	NoFollow LinkRelation = "nofollow"
	// NoOpener indicates that any newly created top-level browsing context which results from following the link will not be an auxiliary browsing context.
	//
	// Reference: [HTML]
	NoOpener LinkRelation = "noopener"
	// NoReferrer indicates that no referrer information is to be leaked when following the link.
	//
	// Reference: [HTML]
	NoReferrer LinkRelation = "noreferrer"
	// Opener indicates that any newly created top-level browsing context which results from following the link will be an auxiliary browsing context.
	//
	// Reference: [HTML]
	Opener LinkRelation = "opener"
	// OpenID2LocalID refers to an OpenID Authentication server on which the context relies for an assertion that the end user controls an Identifier.
	//
	// Reference: [OpenID Authentication 2.0 - Final]
	OpenID2LocalID LinkRelation = "openid2.local_id"
	// OpenID2Provider refers to a resource which accepts OpenID Authentication protocol messages for the context.
	//
	// Reference: [OpenID Authentication 2.0 - Final]
	OpenID2Provider LinkRelation = "openid2.provider"
	// Original the Target IRI points to an Original Resource.
	//
	// An Original Resource is a resource that exists or used to
	// exist, and for which access to one of its prior states may be
	// required.
	//
	// Reference: [RFC7089]
	Original LinkRelation = "original"
	// P3Pv1 refers to a P3P privacy policy for the context.
	//
	// Reference: [The Platform for Privacy Preferences 1.0 (P3P1.0) Specification]
	P3Pv1 LinkRelation = "p3pv1"
	// Payment indicates a resource where payment is accepted.
	//
	// This relation type registration did not indicate a
	// reference.  Requested by Joshua Kinberg and Robert Sayre.  It is
	// meant as a general way to facilitate acts of payment, and thus
	// this specification makes no assumptions on the type of payment or
	// transaction protocol.  Examples may include a web page where
	// donations are accepted or where goods and services are available
	// for purchase. rel="payment" is not intended to initiate an
	// automated transaction.  In Atom documents, a link element with a
	// rel="payment" attribute may exist at the feed/channel level and/or
	// the entry/item level.  For example, a rel="payment" link at the
	// feed/channel level may point to a "tip jar" URI, whereas an entry/
	// item containing a book review may include a rel="payment" link
	// that points to the location where the book may be purchased
	// through an online retailer.
	//
	// Reference: [RFC8288]
	Payment LinkRelation = "payment"
	// Pingback gives the address of the pingback resource for the link context.
	//
	// Reference: [Pingback 1.0]
	Pingback LinkRelation = "pingback"
	// Preconnect used to indicate an origin that will be used to fetch required resources for the link context. Initiating an early connection, which includes the DNS lookup, TCP handshake, and optional TLS negotiation, allows the user agent to mask the high latency costs of establishing a connection.
	//
	// Reference: [HTML]
	Preconnect LinkRelation = "preconnect"
	// PredecessorVersion points to a resource containing the predecessor
	// version in the version history.
	//
	// Reference: [RFC5829]
	PredecessorVersion LinkRelation = "predecessor-version"
	// Prefetch the prefetch link relation type is used to identify a resource that might be required by the next navigation from the link context, and that the user agent ought to fetch, such that the user agent can deliver a faster response once the resource is requested in the future.
	//
	// Reference: [HTML]
	Prefetch LinkRelation = "prefetch"
	// Preload refers to a resource that should be loaded early in the processing of the link's context, without blocking rendering.
	//
	// Additional target attributes establish the detailed fetch properties of the link.
	//
	// Reference: [Preload]
	Preload LinkRelation = "preload"
	// Prerender used to identify a resource that might be required by the next navigation from the link context, and that the user agent ought to fetch and execute, such that the user agent can deliver a faster response once the resource is requested in the future.
	//
	// Reference: [Resource Hints]
	Prerender LinkRelation = "prerender"
	// Prev indicates that the link's context is a part of a series, and
	// that the previous in the series is the link target.
	//
	// Reference: [HTML]
	Prev LinkRelation = "prev"
	// Preview refers to a resource that provides a preview of the link's context.
	//
	// Reference: [RFC6903], section 3
	Preview LinkRelation = "preview"
	// Previous refers to the previous resource in an ordered series
	// of resources.  Synonym for "prev".
	//
	// Reference: [HTML 4.01 Specification]
	Previous LinkRelation = "previous"
	// PrevArchive refers to the immediately preceding archive resource.
	//
	// Reference: [RFC5005]
	PrevArchive LinkRelation = "prev-archive"
	// PrivacyPolicy refers to a privacy policy associated with the link's context.
	//
	// Reference: [RFC6903], section 4
	PrivacyPolicy LinkRelation = "privacy-policy"
	// Profile identifying that a resource representation conforms
	// to a certain profile, without affecting the non-profile semantics
	// of the resource representation.
	//
	// Profile URIs are primarily intended to be used as
	// identifiers, and thus clients SHOULD NOT indiscriminately access
	// profile URIs.
	//
	// Reference: [RFC6906]
	Profile LinkRelation = "profile"
	// Publication links to a publication manifest. A manifest represents structured information about a publication, such as informative metadata, a list of resources, and a default reading order.
	//
	// Reference: [Publication Manifest]
	Publication LinkRelation = "publication"
	// RDAPActive the target is for an RDAP RIR search that filters for the status "active".
	//
	// Reference: [RFC9910]
	RDAPActive LinkRelation = "rdap-active"
	// RDAPBottom refers to the set of child RDAP objects that do not themselves have child objects, in a hierarchy of objects.
	//
	// Reference: [RFC9910]
	RDAPBottom LinkRelation = "rdap-bottom"
	// RDAPDown refers to a set of RDAP child objects in a hierarchy of objects.
	//
	// Reference: [RFC9910]
	RDAPDown LinkRelation = "rdap-down"
	// RDAPTop refers to the topmost RDAP parent object in a hierarchy of objects.
	//
	// Reference: [RFC9910]
	RDAPTop LinkRelation = "rdap-top"
	// RDAPUp refers to an RDAP parent object in a hierarchy of objects.
	//
	// Reference: [RFC9910]
	RDAPUp LinkRelation = "rdap-up"
	// Related identifies a related resource.
	//
	// Reference: [RFC4287]
	Related LinkRelation = "related"
	// Restconf identifies the root of RESTCONF API as configured on this HTTP server.
	// The "restconf" relation defines the root of the API defined in RFC8040.
	// Subsequent revisions of RESTCONF will use alternate relation values to support protocol versioning.
	//
	// Reference: [RFC8040]
	Restconf LinkRelation = "restconf"
	// Replies identifies a resource that is a reply to the context
	// of the link.
	//
	// Reference: [RFC4685]
	Replies LinkRelation = "replies"
	// RuleInput the resource identified by the link target provides an input value to an instance of a rule, where the resource which represents the rule instance is identified by the link context.
	//
	// Reference: [OCF Core Optional 2.2.0]
	RuleInput LinkRelation = "ruleinput"
	// Search refers to a resource that can be used to search through
	// the link's context and related resources.
	//
	// Reference: [OpenSearch]
	Search LinkRelation = "search"
	// Section refers to a section in a collection of resources.
	//
	// Reference: [HTML 4.01 Specification]
	Section LinkRelation = "section"
	// Self conveys an identifier for the link's context.
	//
	// Reference: [RFC4287]
	Self LinkRelation = "self"
	// Service indicates a URI that can be used to retrieve a
	// service document.
	//
	// When used in an Atom document, this relation type specifies
	// Atom Publishing Protocol service documents by default.  Requested
	// by James Snell.
	//
	// Reference: [RFC5023]
	Service LinkRelation = "service"
	// ServiceDesc identifies service description for the context that
	// is primarily intended for consumption by machines.
	//
	// Reference: [RFC8631]
	ServiceDesc LinkRelation = "service-desc"
	// ServiceDoc identifies service documentation for the context that
	// is primarily intended for human consumption.
	//
	// Reference: [RFC8631]
	ServiceDoc LinkRelation = "service-doc"
	// ServiceMeta identifies general metadata for the context that is
	// primarily intended for consumption by machines.
	//
	// Reference: [RFC8631]
	ServiceMeta LinkRelation = "service-meta"
	// SIPTrunkingCapability refers to a capability set document that defines parameters or configuration requirements for automated peering and communication-channel negotiation of the Session Initiation Protocol (SIP).
	//
	// Reference: [RFC9409]
	SIPTrunkingCapability LinkRelation = "sip-trunking-capability"
	// Sponsored refers to a resource that is within a context that is sponsored (such as advertising or another compensation agreement).
	//
	// Reference: [Google Blog post 09-2019]
	Sponsored LinkRelation = "sponsored"
	// Start refers to the first resource in a collection of
	// resources.
	//
	// Reference: [HTML 4.01 Specification]
	Start LinkRelation = "start"
	// Status identifies a resource that represents the context's
	// status.
	//
	// Reference: [RFC8631]
	Status LinkRelation = "status"
	// Stylesheet refers to a stylesheet.
	//
	// Reference: [HTML]
	Stylesheet LinkRelation = "stylesheet"
	// Subsection refers to a resource serving as a subsection in a
	// collection of resources.
	//
	// Reference: [HTML 4.01 Specification]
	Subsection LinkRelation = "subsection"
	// SuccessorVersion points to a resource containing the successor version
	// in the version history.
	//
	// Reference: [RFC5829]
	SuccessorVersion LinkRelation = "successor-version"
	// Sunset identifies a resource that provides information about
	// the context's retirement policy.
	//
	// Reference: [RFC8594]
	Sunset LinkRelation = "sunset"
	// Tag gives a tag (identified by the given address) that applies to
	// the current document.
	//
	// Reference: [HTML]
	Tag LinkRelation = "tag"
	// TermsOfService refers to the terms of service associated with the link's context.
	//
	// Reference: [RFC6903], section 5
	TermsOfService LinkRelation = "terms-of-service"
	// TimeGate the Target IRI points to a TimeGate for an Original Resource.
	//
	// A TimeGate for an Original Resource is a resource that is
	// capable of datetime negotiation to support access to prior states
	// of the Original Resource.
	//
	// Reference: [RFC7089]
	TimeGate LinkRelation = "timegate"
	// TimeMap the Target IRI points to a TimeMap for an Original Resource.
	//
	// A TimeMap for an Original Resource is a resource from which
	// a list of URIs of Mementos of the Original Resource is available.
	//
	// Reference: [RFC7089]
	TimeMap LinkRelation = "timemap"
	// Type refers to a resource identifying the abstract semantic type of which the link's context is considered to be an instance.
	//
	// Reference: [RFC6903], section 6
	Type LinkRelation = "type"
	// Ugc refers to a resource that is within a context that is User Generated Content.
	//
	// Reference: [Google Blog post 09-2019]
	Ugc LinkRelation = "ugc"
	// Up refers to a parent document in a hierarchy of
	// documents.
	//
	// This relation type registration did not indicate a
	// reference.  Requested by Noah Slater.
	//
	// Reference: [RFC8288]
	Up LinkRelation = "up"
	// VersionHistory points to a resource containing the version history
	// for the context.
	//
	// Reference: [RFC5829]
	VersionHistory LinkRelation = "version-history"
	// Via identifies a resource that is the source of the
	// information in the link's context.
	//
	// Reference: [RFC4287]
	Via LinkRelation = "via"
	// Webmention identifies a target URI that supports the Webmention protocol.
	// This allows clients that mention a resource in some form of publishing process
	// to contact that endpoint and inform it that this resource has been mentioned.
	//
	// This is a similar "Linkback" mechanism to the ones of Refback, Trackback, and Pingback.
	// It uses a different protocol, though, and thus should be discoverable through its own link
	// relation type.
	//
	// Reference: [Webmention]
	Webmention LinkRelation = "webmention"
	// WorkingCopy points to a working copy for this resource.
	//
	// Reference: [RFC5829]
	WorkingCopy LinkRelation = "working-copy"
	// WorkingCopyOf points to the versioned resource from which this
	// working copy was obtained.
	//
	// Reference: [RFC5829]
	WorkingCopyOf LinkRelation = "working-copy-of"
)
