package main

import (
	"bytes"
	_ "embed"
	"encoding/csv"
	"log/slog"
	"os"
	"strings"
	"text/template"

	"modernc.org/libc/errno"
)

func main() {
	setLogLevel()

	records, err := parseCSV()
	if err != nil {
		slog.Error("failed to parse input csv", slog.String("err", err.Error()))
		os.Exit(errno.EIO)
	}

	slog.Debug("link relation records parsed successfully", slog.Any("records", records))

	fileContents, err := generateFile(fileParameters{
		PackageName: "linkrelation",
		TypeName:    "LinkRelation",
		Records:     records,
	})
	if err != nil {
		slog.Error("failed to generate file contents", slog.String("err", err.Error()))
		os.Exit(errno.EBADEXEC)
	}

	fp, err := os.Create("definitions.go")
	if err != nil {
		slog.Error("failed to open destination file", slog.String("err", err.Error()))
		os.Exit(errno.EBADF)
	}
	defer fp.Close()

	if _, err = fp.WriteString(fileContents); err != nil {
		slog.Error("failed to write file contents to destination", slog.String("err", err.Error()))
		os.Exit(errno.EBADF)
	}
}

func setLogLevel() {
	var level slog.Level
	switch strings.ToLower(os.Getenv("LOG_LEVEL")) {
	case "debug":
		level = slog.LevelDebug
	case "info":
		level = slog.LevelInfo
	case "warn":
		level = slog.LevelWarn
	case "error":
		level = slog.LevelError
	}
	slog.SetLogLoggerLevel(level)
}

// linkRelationsCSV stores the CSV data exported from https://www.iana.org/assignments/link-relations/link-relations-1.csv
//
//go:embed link-relations-1.csv
var linkRelationsCSV []byte

func parseCSV() ([]linkRelationRecord, error) {
	var linkRelations []linkRelationRecord

	records, err := csv.NewReader(bytes.NewBuffer(linkRelationsCSV)).ReadAll()
	if err != nil {
		return nil, err
	}

	for _, record := range records[1:] {
		linkRelations = append(linkRelations, linkRelationRecord{
			RelationName: record[0],
			Description:  record[1],
			Reference:    record[2],
			Notes:        record[3],
		})
	}

	return linkRelations, nil
}

type linkRelationRecord struct {
	RelationName, Description, Reference, Notes string
}

type fileParameters struct {
	PackageName string
	TypeName    string
	Records     []linkRelationRecord
}

func generateFile(params fileParameters) (string, error) {
	tmpl := template.Must(template.New("file").Funcs(template.FuncMap{
		"TitleCase": func(s string) string {
			if override, ok := customOverrides(s); ok {
				return override
			}

			ss := strings.Split(s, "-")
			for i := range ss {
				ss[i] = toUpper(ss[i])
			}
			return strings.Join(ss, "")
		},
		"DownCaseFirstLetter": func(s string) string {
			return strings.ToLower(s[0:1]) + s[1:]
		},
		"CommentPrefixed": func(s string) string {
			ss := strings.Split(s, "\n")
			for i := range ss {
				ss[i] = strings.TrimSpace(ss[i])
			}
			return strings.Join(ss, "\n\t// ")
		},
	}).Parse(`// Code generated by go generate .internal/tools/generator; DO NOT EDIT.

package {{ .PackageName }}

const (
{{- range .Records }}
	// {{ .RelationName | TitleCase }} {{ .Description | DownCaseFirstLetter | CommentPrefixed }}
	{{- if gt (len .Notes) 0 }}
	//
	// {{ .Notes | CommentPrefixed }}
	{{- end }}
	//
	// Reference: {{ .Reference }}
	{{ .RelationName | TitleCase }} {{ $.TypeName }} = "{{ .RelationName }}"
{{- end }}
)
`))

	data := bytes.NewBuffer([]byte{})
	if err := tmpl.Execute(data, params); err != nil {
		return "", err
	}

	return data.String(), nil
}

func toUpper(s string) string {
	switch s {
	case "rdap":
		return "RDAP"
	case "sip":
		return "SIP"
	}
	return strings.ToUpper(s[0:1]) + s[1:]
}

func customOverrides(s string) (string, bool) {
	if middle, ok := strings.CutPrefix(s, "interval"); ok {
		var hasBy bool
		middle, hasBy = strings.CutSuffix(middle, "by")

		replacement := "Interval" + strings.ToUpper(middle[0:1]) + middle[1:]
		if hasBy {
			replacement += "By"
		}
		return replacement, true
	}

	switch s {
	case "amphtml":
		return "AMPHTML", true
	case "api-catalog":
		return "APICatalog", true
	case "c2pa-manifest":
		return "C2PAManifest", true
	case "convertedfrom":
		return "ConvertedFrom", true
	case "describedby":
		return "DescribedBy", true
	case "dns-prefetch":
		return "DNSPrefetch", true
	case "geofeed":
		return "GeoFeed", true
	case "ice-server":
		return "ICEServer", true
	case "linkset":
		return "LinkSet", true
	case "lrdd":
		return "LRDD", true
	case "modulepreload":
		return "ModulePreload", true
	case "nofollow":
		return "NoFollow", true
	case "noopener":
		return "NoOpener", true
	case "noreferrer":
		return "NoReferrer", true
	case "openid2.local_id":
		return "OpenID2LocalID", true
	case "openid2.provider":
		return "OpenID2Provider", true
	case "p3pv1":
		return "P3Pv1", true
	case "ruleinput":
		return "RuleInput", true
	case "timegate":
		return "TimeGate", true
	case "timemap":
		return "TimeMap", true
	}
	return s, false
}
